image:
  # image.parentRepository -- Docker registry to pull images from
  parentRepository: ghcr.io/jenkins-x

  repository: ghcr.io/jenkins-x-plugins/jx-preview

  # image.tag -- Docker images tag
  tag: latest

  # image.pullPolicy -- Image pull policy
  pullPolicy: IfNotPresent

gcJobs:
  # gcJobs.schedule -- Cron expression to periodically garbage collect `Preview` resources; every 10 minutes by default
  schedule: "*/10 * * * *"

  # gcJobs.failedJobsHistoryLimit -- Drives the failed jobs history limit
  failedJobsHistoryLimit: 1

  # gcJobs.successfulJobsHistoryLimit -- Drives the successful jobs history limit
  successfulJobsHistoryLimit: 3

  # gcJobs.concurrencyPolicy -- Drives the job's concurrency policy
  concurrencyPolicy: Forbid


jxRequirements:
  cluster:
    gitServer: https://github.com
