filepath: ""
environments:
  default:
    values:
    - jx-values.yaml
namespace: jx
repositories:
- name: jxgh
  url: https://jenkins-x-charts.github.io/repo
releases:
- chart: jxgh/jxboot-helmfile-resources
  version: 1.1.255
  name: jxboot-helmfile-resources
  values:
  - ../../versionStream/charts/jxgh/jxboot-helmfile-resources/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/bucketrepo
  version: 0.1.67
  name: bucketrepo
  values:
  - ../../versionStream/charts/jxgh/bucketrepo/values.yaml.gotmpl
  - jx-values.yaml
- chart: jxgh/jx-build-controller
  version: 0.4.7
  name: jx-build-controller
  values:
  - ../../versionStream/charts/jxgh/jx-build-controller/values.yaml.gotmpl
  - jx-values.yaml
templates: {}
renderedvalues: {}
