{{- if .Values.engines.jenkins }}
apiVersion: v1
kind: Service
metadata:
  name: {{ template "jenkinscontroller.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
  {{- with .Values.jenkinscontroller.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: logs
      protocol: TCP
      name: logs
  selector:
    app: {{ template "jenkinscontroller.name" . }}
{{- end }}
