{{- if .Values.poller.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "poller.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "poller.name" . }}
spec:
  replicas: {{ .Values.poller.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ template "poller.name" . }}
  template:
    metadata:
{{- if or .Values.poller.datadog.enabled .Values.poller.podAnnotations }}
      annotations:
{{- if .Values.poller.datadog.enabled }}
        ad.datadoghq.com/poller.logs: '[{"source":"lighthouse","service":"poller"}]'
{{- end }}
{{- if .Values.poller.podAnnotations }}
{{ toYaml .Values.poller.podAnnotations | indent 8 }}
{{- end }}
{{- end }}
      labels:
        app: {{ template "poller.name" . }}
    spec:
      serviceAccountName: {{ template "poller.name" . }}
      terminationGracePeriodSeconds: {{ .Values.poller.terminationGracePeriodSeconds }}
      containers:
      - name: {{ template "poller.name" . }}
        image: {{ tpl .Values.poller.image.repository . }}:{{ tpl .Values.poller.image.tag . }}
        imagePullPolicy: {{ tpl .Values.poller.image.pullPolicy . }}
        args:
          - "--namespace={{ .Release.Namespace }}"
          {{- if .Values.poller.contextMatchPattern }}
          - "--context-match-pattern={{ .Values.poller.contextMatchPattern }}"
          {{- end }}
          {{- if .Values.poller.requireReleaseSuccess }}
          - --require-release-success
          {{- end }}
        ports:
          - name: http
            containerPort: {{ .Values.poller.internalPort }}
            protocol: TCP
        livenessProbe:
          httpGet:
            path: {{ .Values.poller.probe.path }}
            port: http
          initialDelaySeconds: {{ .Values.poller.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.poller.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.poller.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.poller.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.poller.probe.path }}
            port: http
          periodSeconds: {{ .Values.poller.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.poller.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.poller.readinessProbe.timeoutSeconds }}
        env:
        - name: "GIT_KIND"
          value: "{{ .Values.git.kind }}"
        - name: "GIT_SERVER"
          value: "{{ .Values.git.server }}"
{{- if .Values.githubApp.enabled }}
        - name: "GITHUB_APP_SECRET_DIR"
          value: "/secrets/githubapp/tokens"
{{- else }}
        - name: "GIT_USER"
          value: {{ .Values.user }}
{{- if .Values.oauthTokenVolumeMount.enabled }}
        - name: "GIT_TOKEN_PATH"
          value: /secrets/lighthouse-oauth-token/oauth
{{- else }}
        - name: "GIT_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.oauthSecretName | default "lighthouse-oauth-token" }}
              key: oauth
{{- end }}
{{- end }}
{{- if .Values.hmacTokenEnabled }}
{{- if .Values.hmacTokenVolumeMount.enabled }}
        - name: "HMAC_TOKEN_PATH"
          value: /secrets/lighthouse-hmac-token/hmac
{{- else }}
        - name: "HMAC_TOKEN"
          valueFrom:
            secretKeyRef:
              name: {{ .Values.hmacSecretName | default "lighthouse-hmac-token" }}
              key: hmac
{{- end }}
{{- end }}
        - name: "JX_LOG_FORMAT"
          value: "{{ .Values.logFormat }}"
        - name: LOG_LEVEL
          value: "{{ .Values.poller.logLevel }}"
        - name: "LOGRUS_FORMAT"
          value: "{{ .Values.logFormat }}"
        - name: LOGRUS_SERVICE
          value: "{{ .Values.logService | default .Chart.Name }}"
        - name: LOGRUS_SERVICE_VERSION
          value: "{{ .Chart.Version }}"
        - name: LOGRUS_STACK_SKIP
          value: "{{ .Values.logStackSkip }}"
{{- if hasKey .Values.poller "env" }}
{{- range $pkey, $pval := .Values.poller.env }}
        - name: {{ $pkey }}
          value: {{ quote  $pval }}
{{- end }}
{{- end }}
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        resources:
{{ toYaml .Values.poller.resources | indent 10 }}
        volumeMounts:
{{- if .Values.githubApp.enabled }}
        - name: githubapp-tokens
          mountPath: /secrets/githubapp/tokens
          readOnly: true
{{- else if .Values.oauthTokenVolumeMount.enabled }}
        - name: lighthouse-oauth-token
          mountPath: /secrets/lighthouse-oauth-token
          readOnly: true
{{- end }}
{{- if and .Values.hmacTokenEnabled .Values.hmacTokenVolumeMount.enabled }}
        - name: lighthouse-hmac-token
          mountPath: /secrets/lighthouse-hmac-token
          readOnly: true
{{- end }}
      volumes:
{{- if .Values.githubApp.enabled }}
      - name: githubapp-tokens
        secret:
          secretName: tide-githubapp-tokens
{{- else if .Values.oauthTokenVolumeMount.enabled }}
      - name: lighthouse-oauth-token
        secret:
          secretName: lighthouse-oauth-token
{{- end }}
{{- if and .Values.hmacTokenEnabled .Values.hmacTokenVolumeMount.enabled }}
      - name: lighthouse-hmac-token
        secret:
          secretName: {{ .Values.hmacSecretName | default "lighthouse-hmac-token" }}
{{- end }}
{{- with .Values.poller.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.poller.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.poller.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
{{- end }}
