apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "webhooks.name" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
    app: {{ template "webhooks.name" . }}
{{- if  .Values.webhooks.labels }}
{{ toYaml .Values.webhooks.labels | indent 4 }}
{{- end }}
  annotations:
{{- if not .Values.hmacSecretName }}
    checksum/config: {{ include (print $.Template.BasePath "/hmacsecret.yaml") . | sha256sum }}
{{- end }}
spec:
  replicas: {{ .Values.webhooks.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "webhooks.name" . }}
  template:
    metadata:
      labels:
        app: {{ template "webhooks.name" . }}
{{- if  .Values.webhooks.podLabels }}
{{ toYaml .Values.webhooks.podLabels | indent 8 }}
{{- end }}
{{- if or .Values.webhooks.podAnnotations .Values.podAnnotations }}
      annotations:
{{- if .Values.webhooks.podAnnotations }}
{{ toYaml .Values.webhooks.podAnnotations | indent 8 }}
{{- end }}
{{- if .Values.podAnnotations }}
{{ toYaml .Values.podAnnotations | indent 8 }}
{{- end }}
{{- end }}
    spec:
      serviceAccountName: {{ template "webhooks.name" . }}
      containers:
      - name: {{ template "webhooks.name" . }}
        image: {{ tpl .Values.webhooks.image.repository . }}:{{ tpl .Values.webhooks.image.tag . }}
        imagePullPolicy: {{ tpl .Values.webhooks.image.pullPolicy . }}
        args:
          - "--namespace={{ .Release.Namespace }}"
        env:
          - name: "GIT_KIND"
            value: "{{ .Values.git.kind }}"
          - name: "LH_CUSTOM_TRIGGER_COMMAND"
            value: "{{ .Values.webhooks.customDeploymentTriggerCommand }}"
          - name: "GIT_SERVER"
            value: "{{ .Values.git.server }}"
{{- if .Values.githubApp.enabled }}
          - name: "GITHUB_APP_SECRET_DIR"
            value: "/secrets/githubapp/tokens"
{{- else }}
          - name: "GIT_USER"
            value: {{ .Values.user }}
{{- if .Values.oauthTokenVolumeMount.enabled }}
          - name: "GIT_TOKEN_PATH"
            value: /secrets/lighthouse-oauth-token/oauth
{{- else }}
          - name: "GIT_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.oauthSecretName | default "lighthouse-oauth-token" }}
                key: oauth
{{- end }}
{{- end }}
{{- if .Values.hmacTokenEnabled }}
{{- if .Values.hmacTokenVolumeMount.enabled }}
          - name: "HMAC_TOKEN_PATH"
            value: /secrets/lighthouse-hmac-token/hmac
{{- else }}
          - name: "HMAC_TOKEN"
            valueFrom:
              secretKeyRef:
                name: {{ .Values.hmacSecretName | default "lighthouse-hmac-token" }}
                key: hmac
{{- end }}
{{- end }}
          - name: "JX_LOG_FORMAT"
            value: "{{ .Values.logFormat }}"
          - name: "LOGRUS_FORMAT"
            value: "{{ .Values.logFormat }}"
          - name: LOGRUS_SERVICE
            value: "{{ .Values.logService | default .Chart.Name }}"
          - name: LOG_LEVEL
            value: "{{ .Values.webhooks.logLevel }}"
          - name: LOGRUS_SERVICE_VERSION
            value: "{{ .Chart.Version }}"
          - name: LOGRUS_STACK_SKIP
            value: "{{ .Values.logStackSkip }}"
{{- if hasKey .Values "env" }}
{{- range $pkey, $pval := .Values.env }}
          - name: {{ $pkey }}
            value: {{ quote $pval }}
{{- end }}
{{- end }}
        envFrom:
        - secretRef:
            name: jx-boot-job-env-vars
            optional: true
        ports:
        - containerPort: {{ .Values.webhooks.service.internalPort }}
        livenessProbe:
          httpGet:
            path: {{ .Values.webhooks.probe.path }}
            port: {{ .Values.webhooks.service.internalPort }}
          initialDelaySeconds: {{ .Values.webhooks.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.webhooks.livenessProbe.periodSeconds }}
          successThreshold: {{ .Values.webhooks.livenessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.webhooks.livenessProbe.timeoutSeconds }}
        readinessProbe:
          httpGet:
            path: {{ .Values.webhooks.probe.path }}
            port: {{ .Values.webhooks.service.internalPort }}
          periodSeconds: {{ .Values.webhooks.readinessProbe.periodSeconds }}
          successThreshold: {{ .Values.webhooks.readinessProbe.successThreshold }}
          timeoutSeconds: {{ .Values.webhooks.readinessProbe.timeoutSeconds }}
        resources:
{{ toYaml .Values.webhooks.resources | indent 12 }}
        volumeMounts:
{{- if .Values.githubApp.enabled }}
          - name: githubapp-tokens
            mountPath: /secrets/githubapp/tokens
            readOnly: true
{{- else if .Values.oauthTokenVolumeMount.enabled }}
          - name: lighthouse-oauth-token
            mountPath: /secrets/lighthouse-oauth-token
            readOnly: true
{{- end }}
{{- if and .Values.hmacTokenEnabled .Values.hmacTokenVolumeMount.enabled }}
          - name: lighthouse-hmac-token
            mountPath: /secrets/lighthouse-hmac-token
            readOnly: true
{{- end }}
      volumes:
{{- if .Values.githubApp.enabled }}
        - name: githubapp-tokens
          secret:
            secretName: tide-githubapp-tokens
{{- else if .Values.oauthTokenVolumeMount.enabled }}
        - name: lighthouse-oauth-token
          secret:
            secretName: lighthouse-oauth-token
{{- end }}
{{- if and .Values.hmacTokenEnabled .Values.hmacTokenVolumeMount.enabled }}
        - name: lighthouse-hmac-token
          secret:
            secretName: {{ .Values.hmacSecretName | default "lighthouse-hmac-token" }}
{{- end }}
      terminationGracePeriodSeconds: {{ .Values.webhooks.terminationGracePeriodSeconds }}
{{- with .Values.webhooks.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.webhooks.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
{{- end }}
{{- with .Values.webhooks.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
{{- end }}
