kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "gcJobs.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
  - delete
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - preview.jenkins.io
  resources:
  - previews
  verbs:
  - create
  - delete
  - list
  - update
  - get
  - watch
  - patch
